# The file is generated by:
#   python -m gen tag 2.26.2
let
  lib = import ../../common/lib.nix;

  version = "2.26.2";
  hash = "sha256-yuIv7t/5qrYdNQn7VjtY29ja+4Nj/NNt9t6tNq7vsJs=";

  # https://raw.githubusercontent.com/pantsbuild/pants/release_2.26.2/src/rust/engine/rust-toolchain
  rustVersion = "1.85.0";
  cargoLock = {
    # https://raw.githubusercontent.com/pantsbuild/pants/release_2.26.2/src/rust/engine/Cargo.lock
    lockFile = ./Cargo.lock;
    outputHashes = {
      "deepsize-0.2.0" = "sha256-E73xdzYfpJASps3yz6sjL48Kimy44F2LvxndWzgV3dU=";
      "deepsize_derive-0.1.2" = "sha256-E73xdzYfpJASps3yz6sjL48Kimy44F2LvxndWzgV3dU=";
      "lmdb-rkv-0.14.0" = "sha256-yj0+3wRQkAyp5EYOe2WQeUt1D/3cXZK0XrH6qcxhaWw=";
      "lmdb-rkv-sys-0.11.0" = "sha256-c9lKJuE74Xp/sIwSFXFsl2EKffY3oC7Prnglt6p1Ah0=";
      "notify-5.0.0-pre.15" = "sha256-LG6e3dSIqQcHbNA/uYSVJwn/vgcAH0noHK4x3QQdqVI=";
      "prodash-16.0.0" = "sha256-Dkn4BmsF1SnSDAoqW5QkjdzGHEq41y7S20Q/DkRCpVQ=";
      "tree-sitter-dockerfile-0.2.0" = "sha256-UQSdcOWRH1QsFWVgxyx9/E7419Ue5zi79ngWNsWuQBc=";
    };
  };
  patches = [
    ../../common/patch-process-manager.txt
    ../../common/patch-coursier-fetch.txt
    ../../common/patch-process.txt
    ../../common/patch-jdk-sh.txt
    ../../common/patch-process-extra-env.txt
  ];
in
  lib.makePants {
    inherit version hash rustVersion cargoLock patches;
  }
